CRUD EntityFramework/Models/products.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_EntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int ID { get; set; }
        public string PRODUCT { get; set; }
        public int QUANTITY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}

CRUD EntityFramework/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRUD_EntityFramework.Models;
using CRUD_EntityFramework.Models.ViewModels;

namespace CRUD_EntityFramework.Controllers
{
    public class productsController : Controller
    {
        //
        // GET: /products/
        public ActionResult Index()
        {
            List<ListTablaViewModels> lst;
            using (EntityFrameworkTestEntities2 db = new EntityFrameworkTestEntities2())
            {
                lst = (from d in db.products
                           select new ListTablaViewModels
                           {
                               Id = d.ID,
                               Product = d.PRODUCT,
                               Quantity = d.QUANTITY,
                               Modified_Date = d.MODIFIED_DATE.Value
                           }).ToList();
            }
            return View(lst);
        }

        public ActionResult Nuevo() 
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(TablaViewModels model)
        {
            try 
            {
                if (ModelState.IsValid) 
                {
                    using (EntityFrameworkTestEntities2 db = new EntityFrameworkTestEntities2()) 
                    {
                        var oProduct = new products();
                        oProduct.PRODUCT = model.Product;
                        oProduct.QUANTITY = model.Quantity;
                        oProduct.MODIFIED_DATE = model.Modified_Date;

                        db.products.Add(oProduct);
                        db.SaveChanges();
                    }
                    return Redirect("~/products/");
                }
                return View(model);
            }
            catch(Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Editar(int Id)
        {
            TablaViewModels model = new TablaViewModels();
            using(EntityFrameworkTestEntities2 db = new EntityFrameworkTestEntities2())
            {
                var oProduct = db.products.Find(Id);
                model.Product = oProduct.PRODUCT;
                model.Quantity = oProduct.QUANTITY;
                model.Modified_Date = oProduct.MODIFIED_DATE.Value;
                model.Id = oProduct.ID;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(TablaViewModels model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (EntityFrameworkTestEntities2 db = new EntityFrameworkTestEntities2())
                    {
                        var oProduct = db.products.Find(model.Id);
                        oProduct.PRODUCT = model.Product;
                        oProduct.QUANTITY = model.Quantity;
                        oProduct.MODIFIED_DATE = model.Modified_Date;

                        db.Entry(oProduct).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return Redirect("~/products/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int Id)
        {
            using (EntityFrameworkTestEntities2 db = new EntityFrameworkTestEntities2())
            {
                var oProduct = db.products.Find(Id);
                db.products.Remove(oProduct);
                db.SaveChanges();
            }
            return Redirect("~/products/");
        }
	}
}

CRUD EntityFramework/Views/products/Editar.cshtml
@model CRUD_EntityFramework.Models.ViewModels.TablaViewModels
@{
    ViewBag.Title = "Editar";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Editar", "products", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d=>d.Id)
            @Html.LabelFor(d => d.Product)
            @Html.TextBoxFor(d => d.Product, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Quantity)
            @Html.TextBoxFor(d => d.Quantity, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Modified_Date) <br />
            @Html.EditorFor(d => d.Modified_Date, "", new { @class = "form-control" })

            <div style="padding:5px;">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

CRUD EntityFramework/Views/products/Index.cshtml
@model List<CRUD_EntityFramework.Models.ViewModels.ListTablaViewModels>
    @{
        ViewBag.Title = "CRUD Entity Framework";
    }

<h2>@ViewBag.Title</h2>
<div class="row" style="padding:5px;">
    <a href="~/products/Nuevo" class="btn btn-primary">Nuevo</a>    
</div>
<div class="row">
        <div class="col-md-12">
            <table class="table">
                <tr>
                    <th>ID</th>
                    <th>PRODUCT</th>
                    <th>QUANTITY</th>
                    <th>MODIFIED_DATE</th>
                    <th></th>
                </tr>
                @foreach (var oElemento in Model)
                {
                    <tr>
                        <th>@oElemento.Id</th>
                        <th>@oElemento.Product</th>
                        <th>@oElemento.Quantity</th>
                        <th>@oElemento.Modified_Date</th>
                        <th>
                            <a href="~/products/Editar/@oElemento.Id" class="btn btn-default">Editar</a>  
                            <a href="~/products/Eliminar/@oElemento.Id" class="btn btn-danger">Borrar</a>  
                        </th>
                    </tr>
                }
            </table>
        </div>
</div>


CRUD EntityFramework/Views/products/Nuevo.cshtml
@model CRUD_EntityFramework.Models.ViewModels.TablaViewModels
@{
    ViewBag.Title = "Nuevo";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Nuevo", "products", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.LabelFor(d => d.Product)
            @Html.TextBoxFor(d => d.Product, "", new { @class = "form-control"})
            @Html.LabelFor(d => d.Quantity)
            @Html.TextBoxFor(d => d.Quantity, "", new { @class = "form-control" })
            @Html.LabelFor(d => d.Modified_Date) <br />
            @Html.EditorFor(d => d.Modified_Date, "", new { @class = "form-control" })

            <div style="padding:5px;">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


        